### ISSUE TITLE
bug? with the option "Particle size distribution"

### ISSUE THREAD

**Issue by ChumakovAP** [scgmlz/BornAgain#1175]
### Expected behavior
The goal is to use one of the particle form factors in conjunction with the "particle size" option for consistent simulation and fitting. There is a ready-made example in the section Reference materials called Cylinders with a size distribution. It works if you transfer it entirely from the above section. It functions the ability to analyze particle parameters and particle distribution with subsequent visual changes in the 3D Viewer and simulation.

### Actual behavior
However, if you try to remove the Particle object from the imported finished assembly and replace it with any other (even by a new cylindrical particle again), the 3D model gives an error and the Particle Distribution section stops working, as well as participates in the simulation, does not affect the result (please see the picture in the attachments). 
Will you be so kind as to tell me, please, is this some kind of bug in the program or am I doing something wrong? Thank you

**Comment by gpospelov** [comment]
Thanks for reporting this. We will look into that. Could you please attach the picture you mention, and the platform affected. Was it Windows? Thanks!

**Comment by ChumakovAP** [comment]
yes, it was Windows 10 with installed Anaconda at two different PC.
![BornAgain-error](https://user-images.githubusercontent.com/77390222/104707530-ccb44880-571c-11eb-8e11-a9352db6b193.png)

**Comment by gpospelov** [comment]
Hi,

I think it is expected behavior. After you have removed a particle, and then have returned it back, `ParticleDistribution` has to be further adjusted. One has to define which parameter of the attached particle should be `Distributed parameter`.

<img width="349" alt="Screenshot_20210118_121133" src="https://user-images.githubusercontent.com/15112484/104908375-aa256800-5986-11eb-881c-7d0a9c9bf933.png">

If you attach the cylinder again, select material and cylinder size as before, and set `Distributed parameter` to `Particle/Cylinder/Radius`, then the simulation will work again and results must be identical to the previous one.

Regards,
Gennady

**Comment by gpospelov** [comment]
I consider the issue as resolved. Please let us know if you need more help.

**Comment by ChumakovAP** [comment]
Dear Gennady, 

Sorry for the late reply. Yes, now it works, thank you. 
It does not work sometimes with some of the parameters, like the variation of the radius in the truncated sphere, hight only, or keeping the same proportions between the hight and radius and varies of the particle size. But this is some next nonstandard task and it can be solved by the special programmable way according to the description to the BornAgain I think. Thank you very much for your help and this nice program! 

Best regards, Andrei Chumakov
