### ISSUE TITLE
factor of 100 between v1.11 and v1.13

### ISSUE THREAD

**Issue by mikapfl** [scgmlz/BornAgain#680]
Hi,

I'm a bit confused about the normalization of the computations (without slicing). When I run the [buried particles demo](https://www.bornagainproject.org/documentation/sample-models/layered-structures/buried-particles/) in v1.11, the result is quite exactly 100 times the result from v1.13 .
Adding `print(result.array().max())` to the script I can quantify the difference:
```
$ PYTHONPATH=~/.local/old/lib/BornAgain-1.11/ LD_LIBRARY_PATH=~/.local/old/lib/BornAgain-1.11/ python3 buried_particles.py
0.002347614006775734
$ PYTHONPATH=~/.local/lib/BornAgain-1.13/ LD_LIBRARY_PATH=~/.local/lib/BornAgain-1.13/ python3 buried_particles.py
2.3476140067757343e-05
```

Is there a reason for this difference?

I do not see the same difference when using automatic slicing, but I haven't constructed a minimal working example for that yet. If it would be helpful for you, I can also make a mwe showing that v1.11 and v1.13 have the same result when using automatic slicing.

Cheers

Mika

**Comment by waltervh** [comment]
Yes, I know where this comes from:
If the user doesn't set a 2d interference function or explicitly sets the surface density of the particles, a default value is used. The default used to be 1particle/nm^2, but was later changed to 0.01particle/nm^2. The latter value is more realistic, since 10nm is a very typical size of nanoparticles.
Since this surface density comes into play as a multiplicative factor during the computation, this explains the factor of 100 you observe.

**Comment by mikapfl** [comment]
Hi Walter,

thanks for your reply. That solves my problem. (-:

Cheers

Mika
