### ISSUE TITLE
Presentation of  Interference 2D  lattice in 3D viewer

### ISSUE THREAD

**Issue by KasperNikolai** [scgmlz/BornAgain#889]
When using Xi in the 'Interference 2D lattice', which suppose to rotate whole lattice relative to the frame X-axis, the only particles are rotated, but the vectors of 2D lattice are not rotated. It is only related to the 3D viewer - simulated spectra seems to be calculated correctly, i.e. with rotated lattice.

**Comment by gpospelov** [comment]
Dear Nikolai,

thank you for your question and for using the issue system,

I can't confirm this behavior. In BornAgain, the rotation of the lattice with respect to the beam (Xi)
leads to the rotation of the lattice vectors, but not particles in lattice nodes. This partially explained in https://www.bornagainproject.org/documentation/working-with-python/interference/lattice1d/
at the end of the tutorial.

(More naturally, of course, would be to rotate the lattice together with its content. But we historically rotate only lattice vectors and user has to apply additional rotation to particles, if necessary).

As far as I can judge, the behavior of 3D view is consistent with that description.

In this example I have lattice_a = 10, lattice_b = 40 and boxes at lattice points
with sizes (2, 4, 3) (along x, y,z) axes.
Angle Xi=0.0

<img width="1044" alt="rectangular-lattice" src="https://user-images.githubusercontent.com/15112484/72723824-f9716680-3b81-11ea-9344-c74f9a4d2c00.png">

In the following example I have the lattice rotated by 90 deg. Boxes are aligned the same, only distances between them have changed, since now shorter lattice_a is aligned along y-axis.

<img width="1044" alt="rectangular-lattice-90deg" src="https://user-images.githubusercontent.com/15112484/72724374-6df8d500-3b83-11ea-9139-fabb413539c3.png">

**Comment by gpospelov** [comment]
Great, then I close it. Thank you!
