### ISSUE TITLE
Specular settings question in GISAXS with focused incident or parallel incident beam 

### ISSUE THREAD

**Issue by ChunTingLiu01** [scgmlz/BornAgain#893]
We have faced some problems of using BornAgain to simulate GISAS specular cases.
The specularly reflected intensities can be included together with the non-specular intensities in the GISAS simulations using BornAgain.  
The control panel provided in BornAgain, such a task seems to be a viable one.  

But the cases simulated included both focused incident beam, parallel incident beam on line gratings and on arrays of pillars, none of his results indicates the presence of a specular component in the GISAS.  
So we doubt whether the simulations included the use of  both Monte Carlo  and Python provided by BornAgain or not.
In addition, the incident angles used were either 0.5 DEG or 1.0 DEG.  Since silicon was chosen as the substrate and the incident beam energy was set at that of Aluminum K  line, a strong specular reflection peak is expected at these incident angles.  

I have another related question on the specular reflection calculation; is the calculation based on the average depth profile of the density of the substrate alone or of the entire sample including the nanostructures on top of the substrate?  

Please point out if I did something wrong .Your helps will be greatly appreciated.

The attached file include the python code of using Monte Carlo simulate line gratings and arrays of pillars.
[focused incident beam, parallel incident beam on line gratings and on arrays of pillars.pptx](https://github.com/scgmlz/BornAgain/files/4178692/focused.incident.beam.parallel.incident.beam.on.line.gratings.and.on.arrays.of.pillars.pptx)
[grating.pdf](https://github.com/scgmlz/BornAgain/files/4178700/grating.pdf)
[pillar.pdf](https://github.com/scgmlz/BornAgain/files/4178703/pillar.pdf)

**Comment by ChunTingLiu01** [comment]
> We have faced some problems of using BornAgain to simulate GISAS specular cases.
> The specularly reflected intensities can be included together with the non-specular intensities in the GISAS simulations using BornAgain.
> The control panel provided in BornAgain, such a task seems to be a viable one.
> 
> But the cases simulated included both focused incident beam, parallel incident beam on line gratings and on arrays of pillars, none of his results indicates the presence of a specular component in the GISAS.
> So we doubt whether the simulations included the use of both Monte Carlo and Python provided by BornAgain or not.
> In addition, the incident angles used were either 0.5 DEG or 1.0 DEG. Since silicon was chosen as the substrate and the incident beam energy was set at that of Aluminum K line, a strong specular reflection peak is expected at these incident angles.
> 
> I have another related question on the specular reflection calculation; is the calculation based on the average depth profile of the density of the substrate alone or of the entire sample including the nanostructures on top of the substrate?
> 
> Please point out if I did something wrong .Your helps will be greatly appreciated.
> 
> The attached file include the python code of using Monte Carlo simulate line gratings and arrays of pillars.
> [focused incident beam, parallel incident beam on line gratings and on arrays of pillars.pptx](https://github.com/scgmlz/BornAgain/files/4178692/focused.incident.beam.parallel.incident.beam.on.line.gratings.and.on.arrays.of.pillars.pptx)
> [grating.pdf](https://github.com/scgmlz/BornAgain/files/4178700/grating.pdf)
> [pillar.pdf](https://github.com/scgmlz/BornAgain/files/4178703/pillar.pdf)

**Comment by rbeerwerth** [comment]
Thank you for pointing this out.
We will look into the issue and come back to you as soon as possible.
Best

**Comment by gpospelov** [comment]
Thank you very much for your question. We confirm your observation that unspecular data can be larger than the data containing specular contribution.

This is connected with the following:

#### Specular peak amplitude is calculated in BornAgain in a simplified way

+ Calculations do not account for diminishing of specular amplitude due to out-of-specular scattering.
+ Calculations do not account for coherent interference between specular, diffuse scattering and interference from particles.
+ As a consequence, the specular amplitude corresponds simply to refraction coefficient from the top layer.

Thus, when you are simulating GISAS pattern without specular peak you get detector bin amplitudes corresponding to out-of-specular scattering. When you are simulating GISAS pattern with specular peak ON, you get simplified specular amplitude in corresponding detector bins, no out-of-specular part added.

In principle, one could sum-up amplitude in corresponding detector bins manually, to treat diffuse and specular parts in incoherent way. But this in turn would lead to the situation, when total bin intensity could be larger than incoming beam amplitude.

We will implement a better treatment of specular peak in following releases. However, we can't give any estimations, when it can happen. Theoretical treatment and modifications to the code will be highly nontrivial.

As for your second question, specular reflection is calculated using material of layers alone. To switch to average layer material, which take material of particles into the consideration, one has to change simulation option from "Ambient layer material" to "Average layer material" in Simulation window.
