### ISSUE TITLE
Running python script via VS Code

### ISSUE THREAD

**Issue by Apostolo5** [scgmlz/BornAgain#894]
Dear BornAgain team,

I first would like to thank you for the wonderful efforts in developing this platform to a very user-friendly level, including every finetuning from GUI, Documentation, examples and availability to assist! Keep up the good work!

I encounter a problem.  My PC operates with Windows. I tried to run a python script for a simulation via VS Code (using Anaconda Navigator), but as soon as the script starts to runs (import bornagain as ba), I encounter the error:
  "ModuleNotFoundError: No module named 'bornagain' "

Does this relate with the fact that the actual BornAgain program and the python script of the simulation are found in different directories?

Thank you in advance,
Apostolos Vagias (FRM2)

![BornAgain_VSCode](https://user-images.githubusercontent.com/61276654/74967791-fa641500-5419-11ea-8606-1cd5b3d904e5.png)

**Comment by juanmcloaiza** [comment]
Dear Apostolos,


Thank you for using or github page and for sharing the screenshots I am going to show in this reply. 

The specific issue you have encountered was solved by:

1. Adding the `BornAgain` directory to the `PYTHONPATH` environment variable.
2. Adding the `Anaconda` directories to the `PATH` environment variable (not always encouraged).


This is a not so uncommon trap; luckily you are on site and it has been easy for me to personally assist you. In the following I give the details --please feel free to add or comment on anything I may have missed or needs clarification.


All the best,
Juan


## 1. Creating and Editing the `PYTHONPATH` environment variable:

In order to do this **in Windows**, we have searched the environment variable settings in the Windows search bar (next to the *start* window icon, start typing *env*, and the environment variables settings will show. In our case, we have needed to type the German word equivalent *Umgebungsvariablen*). **N.B.:** Be sure to select the "User" environment variables settings, as opposed to the "System" ones. Otherwise you may not be able to modify anything if you don't have administrator privileges:

![OpenEnvironmentVariableSettings](https://user-images.githubusercontent.com/14291849/75136372-d0924300-56e4-11ea-80f4-30a5978dc45d.png)

Once in the environment variable settings, create a new environment variable called `PYTHONPATH`, if it does not exist already, and edit it to contain the path to the directory where BornAgain is installed --usually `C:\BornAgain-<version number>\python`:

![CreateAndEditPythonpath](https://user-images.githubusercontent.com/14291849/75136401-e9025d80-56e4-11ea-825c-bfeed1c0d08d.png)

**N.B.** If `PYTHONPATH` exists, add a semicolon after the last path and type the bornagain installation path, after it, e.g.

```C:\some\other\path;C:\and\yet\another;C:\BornAgain-<version number>\python```

**Explanation:** The `PYTHONPATH` environment variable tells the python interpreter where to look for additional modules that are external to your particular python installation or environment. 

This should suffice to tell where BornAgain is located to all python interpreters you may have installed.

## 2. Adding Anaconda to the `PATH` environment variable:

Changing the `PYTHONPATH` solved the issue for the interpreter `C:\Python37\python.exe`, but a further problem was encountered when trying to use the python interpreter provided by Anaconda, `~\AppData\[...]\anaconda3\python.exe`, as the command `conda` was not found in the `PATH` directories.

![TwoDifferentInterpreters](https://user-images.githubusercontent.com/14291849/75136449-0e8f6700-56e5-11ea-9a25-244d48031346.png)

Before doing anything else, try using the Anaconda command prompt or Anaconda navigator to start Visual Studio Code. This will provide the correct Python environment. **N.B.** The Anaconda navigator and the Anaconda prompt can be found by typing "Anaconda" in the Windows search bar.

If that does not work, the recommended approach is to start from scratch and follow the [BornAgain tutorial](https://www.bornagainproject.org/documentation/getting-started/installation/windows/python-anaconda/). After that, use the Anaconda command prompt or Anaconda navigator to start VSCode.

Users who still prefer to save time and avoid starting from scratch, may add the Anaconda paths to the `PATH` environment variable. **Caution**: As this way of proceeding IS NOT encouraged, I won't give any more details. You should follow only if you know what you are doing. 

To add the Anaconda paths to the `PATH` environment variable, follow the same procedure as for `PYTHONPATH`. **N.B.** Do not re-arrange (e.g. shift up/down) the existing defined fields, only add the new `Anaconda` paths below them:

![AddAnacondaPaths](https://user-images.githubusercontent.com/14291849/75136496-34b50700-56e5-11ea-99bb-9566cb611751.png)

**N.B.** The precise location of the Anaconda paths may vary, look for them using the Anaconda
command prompt.

**Comment by Apostolo5** [comment]
Dear Juan, thank you very much for this meticulous response! Thank you and the BornAgain group! Keep up the good work!
