### ISSUE TITLE
Issue with specular neutron reflectometry simulation of rotated truncated spheres

### ISSUE THREAD

**Issue by Nparacini** [scgmlz/BornAgain#899]
Hi, I am trying to simulate some specular neutron reflection from a model made of core shell particles on a surface at the silicon/D2O interface (see 3D model and Python script attached)

I can get the NR profile simulated OK with a simplified version of the model which does not included a rotated object as a part of the core shell model.

When I add the rotated hemi sphere as part of the core shell model (which has to be rotated 180 deg to be on the right side of the particle) i get the following error:

> JobRunner::start() -> Simulation failed with exception throw:
> 
> TruncatedSphere::createSlicedFormFactor error: not supported for the given rotation!

The GISANS simulations run smoothly with both models, it's just the NR that gives problems with the rotated truncated sphere. I also tried changing the truncated hemi sphere to a hemi ellipsoid and shaped it as a hemi sphere which produced the same error in the simulated NR.

Is there a way of fixing this so that I can use a rotated hemisphere in the simulations? 

Here's a PPT with a summary of the issue 
[NR rotation issue.pptx](https://github.com/scgmlz/BornAgain/files/4287610/NR.rotation.issue.pptx)

Thank you!

Nico

**Comment by gpospelov** [comment]
Such error happens when the particle of complex shape starts to cross the interface. Only simple shape particles can cross interfaces. Complex shape particles have to be fully enclosed in the layer bulk and shouldn't touch interface.

In BornAgain the shape is considered simple if it can be sliced by the interface plane into parts that can also be presented via another particle shape. Basically it leaves us with spheres, box, cylinders and pyramids, possibly z-rotated.

I assume that your truncated sphere is y-rotated and slightly touches the interface.

I tried something in the same line with coreshell particle, making sure that it is inside the bulk, and it works.

<img width="1044" alt="coreshell" src="https://user-images.githubusercontent.com/15112484/75975924-b2dd8e80-5ed9-11ea-8f59-ce62d8cd122b.png">

There is also an option to simulate the same using ParticleComposition, but I'm not sure if it has more sense.
<img width="1044" alt="particlecomposition" src="https://user-images.githubusercontent.com/15112484/75975938-b83ad900-5ed9-11ea-886b-b132b2fa8eb6.png">

**Comment by Nparacini** [comment]
All clear, thank you!

**Comment by gpospelov** [comment]
Great, then closing.
