### ISSUE TITLE
Question to resolution functions

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#912]
I have two questions about the ParameterDistribution functions provided in BornAgain:
1. Where are the samples placed within the resolution and is that the
     same for all distributions? (i.e. is it correct that Gaussian with 5
     samples and sigma factor 2 has samples at -2sigma, -sigma, 0, sigma,
     +2sigma. Is that true for e.g. Gate as well, where sigma is less meaningfull?)  
2. What is the definition of the Trapezoid parameters. Is middle width
     the full size of the plateau or is it added on both sides of the
     center. Is Left/RightWidth measured from the end of the plateau or
     from the center?

It would be very helpful if the Documentation included a plot for each distribution function with markings for the parameters so the definition is clear.

**Comment by mganeva** [comment]
**1.**
Sample points for distributions in BornAgain are placed in the following way. First, boundaries (Xmin, Xmax) for each distribution are computed. Computation takes into account properties of the particular distribution and limitations set by user (for example, user may want to consider only the positive sample points and sets an appropriate limit). For Gaussian distribution boundaries are computed as:
```
Xmin = max(mu - sigma_factor*sigma, Xmin_limit)
Xmax = min(mu + sigma_factor*sigma, Xmax_limit)
```
For a Gate distribution there is no parameter `sigma`, since it indeed would not make any sence. Boundaries for this distribution are specified just as (Xmin, Xmax). Thus, BornAgain will consider the following boundaries:
```
Xmin = max(Xmin, Xmin_limit)
Xmax = min(Xmax, Xmax_limit)
``` 
After the boundaries (Xmin, Xmax) are determined, equidistant sample points are computed in the way the same for all distributions:
```
Xk = Xmin + k*(Xmax - Xmin)/(number_of_samples - 1)
```
where `k` is the number of the particular sample point and varies in the range from 0 to `number_of_samples - 1`. See also the [source code](https://github.com/scgmlz/BornAgain/blob/22ba82fe1efc8a6a7fefee223fd2ab195b3ed92a/Core/Parametrization/Distributions.cpp) starting from line 66 for details.

**2.**
The middle width for Trapezoid distribution is indeed the full size of the plateau. Left and right widths are measured starting from the ends of plateau.

Detailed description of parameters for Trapezoid and other distributions you may find in the [tutorial](https://github.com/scgmlz/BornAgain-tutorial/blob/master/ba-school-2018/day_1/gui_basics_1_M/GUI_particles.ipynb) I've prepared for the BornAgain school 2018. You are right, it should be moved to the BornAgain web page at some point.

**Comment by aglavic** [comment]
Hi Marina,

thanks for the detailed description. I didn't realize there was this nice dialog in the GUI to display the distributions and sampling.
Now everything is clear.
