### ISSUE TITLE
BornAgain on high performance computer

### ISSUE THREAD

**Issue by aglavic** [scgmlz/BornAgain#914]
I'm trying to run complex simulations on a cluster node with 72 cores. Unfortunately I do not see the expected performance gain when increasing the number of threads above ~20 and the node CPU usage stays around 20-30% (top).

I'm not sure if this is unexpected behavior. I also saw that there is an option to use MPI, but I didn't find a description how this can be done.

### Expected behavior
Computation (Wal) time scales approximately linear with number of threads used and total CPU time about constant. As the simulation includes parameter distributions there is no obvious reason why this should level off quickly.

### Actual behavior
Running the same model with different setNumberOfThreads values I receive the following toatl CPU and Wall times:
#Threads    CPU total     Wall
8                 10min-25s    1min-32s
16               10min-36s    50s
24               11min-16s    39s
48               13min-16s    1min-1s
72               15min-58s    56s

### Platforms affected
Linux x86_64 kernel 2.6.32-696.18.7.el6.x86_64

**Comment by gpospelov** [comment]
Scaling depends on sample geometry. It scales well for some, and unfortunately not that good for others.

## About multi-threading and performance

Multithreading in BornAgain is implemented using the "embarrassingly parallel" algorithm. The detector pixels are distributed between threads in equal proportion for every single simulation. If the settings contain, for example, wavelength distribution with 10 points, then the simulation will be executed 10 times. Every single simulation will go multithread, summing up all single simulation will go single-threaded. 

If the detector is relatively small, sample is simple, and the number of wavelength distribution points is large, then overhead on starting threads, summing up the result, will be too big.

I did an investigation on home PC:
Sample_1: detector 512x512, complicated sample.
Threads 1, 2, 4, 6, 8, 12, 14, 16: 100%, 99%, 98%, 93%, 89%, 82%, 78%, 75%, 74%
Where the performance is given in percent from maximum achievable at a given number of threads. 100% means perfect scaling with number of threads. (We are not talking about hyper-threading issues here, or degradation due to common cache sharing between cores on some architectures, for simplicity).

Sample_2: detector 128x128, simple sample, 100 points in the wavelength distribution
Threads 1, 2, 4, 6, 8, 12, 14, 16: 100%, 88%, 75%, 69%, 41%, 33%, 27%, %22, 19%

Clearly, multi-threading is not very helpful and we have to do better here.

## About MPI

MPI is implemented in BornAgain simulations. It will give benefits on a cluster with multiple nodes (processors on different motherboards). The issues mentioned above will be also applicable there. To use MPI one have to compile BornAgain with BORNAGAIN_MPI=ON, and run it as a C++ program (see https://github.com/scgmlz/BornAgain/tree/master/Tests/Functional/Core/MPI).

Running it in Python as MPI is possible. Python has to be compiled and run in MPI mode itself. If there is an interest, I can provide an MPI Python example - as soon as I have access to cluster with such support.

**Comment by aglavic** [comment]
Ah, not this makes sense. I reduced the simulation size on the detector to the important areas to speed it up. When using the full detector size I see a larger gain for more cores.

If I understand you correctly, there would no performance benefit expected when running it through MPI on one single node, right? Then I'll keep it as it is.

**Comment by gpospelov** [comment]
Right, MPI will not help. I will try to investigate multi-threading performance. I should be absolutely possible to achieve much better scaling in the parameter distribution case. It's shame not to make use of so many cores in hands. I suggest to let this issue hanging for a while.

**Comment by aglavic** [comment]
Great, let me know if you want me to run some test cases. The data above probably has quite some high error bars, running it through Jupyter notebook with python time function.

**Comment by aglavic** [comment]
I can confirm that the limitation I've seen can be traces back to using a small ROI. I've run the two test below, first one with a ROI around a peak and 100 resolution point, the other with no ROI over the whole detector (ROI is 690pix, detector 701²):

> Test speed for ROI
>  1: 1.3 s ± 2.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  2: 1.77 s ± 68.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  4: 1.6 s ± 18.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  8: 1.28 s ± 8.91 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 16: 1.25 s ± 122 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 24: 1.18 s ± 22.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 32: 1.21 s ± 8.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> Test speed everything, no resolution
>  1: 6.41 s ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  2: 4.12 s ± 37.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  4: 2.38 s ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
>  8: 1.59 s ± 28.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 16: 1.21 s ± 4.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 24: 1.1 s ± 2.33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 32: 1.03 s ± 3.72 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 48: 989 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
> 72: 987 ms ± 87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by jwuttke** [comment]
No action in the foreseeable future.
